source 'https://rubygems.org'
git_source(:github) { |repo_path| "https://github.com/#{repo_path}.git" }

gem 'rails'
gem 'pg'
gem 'webpacker'
<%= @katapult -%>

# Internals and security
gem 'exception_notification'

# Models
gem 'active_type'
gem 'assignable_values'
gem 'edge_rider'
gem 'has_defaults'
gem 'modularity'

# Views
gem 'haml-rails'
gem 'will_paginate'

# Jobs
gem 'whenever'

group :development do
  gem 'query_diet'
  gem 'better_errors'
  gem 'binding_of_caller', '>= 0.8.0' # Fixes a bug with Ruby 2.5.0

  gem 'web-console'
  gem 'listen', '< 3.2'

  gem 'thin'

  gem 'parallel_tests'

  gem 'guard-livereload', require: false
  gem 'rack-livereload'

  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
end

group :development, :test do
  gem 'byebug'

  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'spring'
end

group :test do
  gem 'database_cleaner'
  gem 'timecop'
  gem 'launchy'

  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber', '< 2.2' # Incompatible with Cucumber Factory
  gem 'cucumber-rails', require: false
  gem 'cucumber_factory'
  gem 'selenium-webdriver'
  gem 'spreewald'

  gem 'rspec'
  gem 'shoulda-matchers', require: false
end

group :deploy do
  gem 'capistrano-rails', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-maintenance'
end
