source 'https://rubygems.org'

<%= @original_gems.join %>

# internal
gem 'exception_notification'
# gem 'admin_cleaner', git: 'git@code.makandra.de:makandra/admin_cleaner.git'

# security
gem 'breach-mitigation-rails'
gem 'safe_cookies'

# better coding
gem 'modularity'
gem 'edge_rider'
gem 'andand'

# models
gem 'has_defaults'
gem 'assignable_values'

# gem 'carrierwave'
# gem 'mini_magick'

# gem 'spreadsheet'
# gem 'vcard'

# views
# gem 'simple_form'
# gem 'nested_form'
gem 'will_paginate'
gem 'makandra-navy', require: 'navy'

# assets
gem 'haml-rails'
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'autoprefixer-rails'
gem 'coffee-rails'
gem 'therubyracer', platform: :ruby
gem 'uglifier'
gem 'compass-rails'
gem 'compass-rgbapng'

group :development do
  gem 'query_diet'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'thin'

  gem 'parallel_tests'
  gem 'guard-livereload', require: false
  gem 'rack-livereload'
  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
end

group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'spring'
end

group :test do
  gem 'database_cleaner'
  gem 'timecop'
  gem 'launchy'

  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber', '< 2' # Incompatible with Cucumber Factory
  gem 'cucumber-rails', require: false
  gem 'cucumber_factory'
  gem 'selenium-webdriver'
  gem 'spreewald'

  gem 'rspec'
  gem 'shoulda-matchers', require: false
end

group :deploy do
  gem 'capistrano-rails', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-maintenance'
end
