source 'https://rubygems.org'

# from original Gemfile
<%= @original_gems.join %>

# engines
gem 'haml-rails'

# internal
gem 'exception_notification'
gem 'breach-mitigation-rails'

# better coding
gem 'modularity'
gem 'edge_rider'
gem 'andand'

# models
gem 'has_defaults'
gem 'assignable_values'

# gem 'carrierwave'
# gem 'mini_magick'

# gem 'spreadsheet'
# gem 'vcard'

# views
# gem 'simple_form'
# gem 'nested_form'
gem 'will_paginate'
gem 'makandra-navy', require: 'navy'

# assets
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'autoprefixer-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'compass-rails', '>= 2.0.4' # fixes "uninitialized constant Sprockets::SassCacheStore"
gem 'compass-rgbapng'

group :development do
  gem 'query_diet'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'thin'

  gem 'guard-livereload', require: false
  gem 'rack-livereload'
  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
end

group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'spring'
end

group :test do
  gem 'parallel_tests'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'launchy'

  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'cucumber_factory'
  gem 'cucumber_spinner'
  gem 'selenium-webdriver'
  gem 'spreewald'

  gem 'rspec'
  gem 'shoulda-matchers', require: false
end
