source 'https://rubygems.org'

# basic
gem 'rails', '~> <%= @rails_version %>'
gem 'mysql2'

# engines
gem 'haml-rails'
gem 'jquery-rails'

# internal
gem 'exception_notification'
gem 'breach-mitigation-rails'

# better coding
gem 'modularity'
gem 'edge_rider'
gem 'andand'

# models
gem 'has_defaults'
gem 'assignable_values'

# gem 'jbuilder'
# gem 'carrierwave'
# gem 'mini_magick'

# gem 'spreadsheet'
# gem 'vcard'

# views
# gem 'simple_form'
# gem 'nested_form'
gem 'will_paginate'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'compass-rails'
  gem 'compass-rgbapng'
end

group :development do
  gem 'query_diet'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'thin' # webrick has warnings when used with 1.9

  gem 'guard-livereload', require: false
  gem 'rack-livereload'
  gem 'pivotal-tracker'
end

group :development, :test do
  gem 'debugger'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end

group :test do
  gem 'parallel_tests'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'launchy'

  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'cucumber_factory'
  gem 'cucumber_spinner'
  gem 'selenium-webdriver'
  gem 'spreewald'

  gem 'rspec_candy'
  gem 'shoulda-matchers'
end
