#!/usr/bin/env ruby

# This file imitates the Rails console to ease debugging the gem.
# Run `script/console` from the gem root to start an IRB with the gem loaded.

# Remember to require classes before using them,
# i.e. run `require 'katapult/wui'` before `Katapult::WUI.new :example_name`.

irb_options = [
  '-Ilib',      # add lib/ to load_path
  '-d',         # set $DEBUG = true
  # Requires
  '-rkatapult/version',
  '-rrails',
  '-rrails/generators',
  '-f'          # don't read ~/.irbrc
]

exec 'irb', *irb_options
