#!/usr/bin/env ruby

irb_options = [
  '-Ilib',      # add lib/ to load_path
  '-d',         # set $DEBUG = true
  '-rkatapult', # require katapult
  '-f'          # don't read ~/.irbrc
]

exec 'irb', *irb_options
